package com.base.mapper;

import com.base.domain.DataDic;
import com.base.domain.DataDicKey;
import com.base.domain.DataDicSchema;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DataDicMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_datadic
     *
     * @mbggenerated Sun Oct 11 19:42:52 CST 2015
     */
    int countByExample(DataDicSchema example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_datadic
     *
     * @mbggenerated Sun Oct 11 19:42:52 CST 2015
     */
    int deleteByExample(DataDicSchema example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_datadic
     *
     * @mbggenerated Sun Oct 11 19:42:52 CST 2015
     */
    int deleteByPrimaryKey(DataDicKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_datadic
     *
     * @mbggenerated Sun Oct 11 19:42:52 CST 2015
     */
    int insert(DataDic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_datadic
     *
     * @mbggenerated Sun Oct 11 19:42:52 CST 2015
     */
    int insertSelective(DataDic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_datadic
     *
     * @mbggenerated Sun Oct 11 19:42:52 CST 2015
     */
    List<DataDic> selectByExample(DataDicSchema example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_datadic
     *
     * @mbggenerated Sun Oct 11 19:42:52 CST 2015
     */
    DataDic selectByPrimaryKey(DataDicKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_datadic
     *
     * @mbggenerated Sun Oct 11 19:42:52 CST 2015
     */
    int updateByExampleSelective(@Param("record") DataDic record, @Param("example") DataDicSchema example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_datadic
     *
     * @mbggenerated Sun Oct 11 19:42:52 CST 2015
     */
    int updateByExample(@Param("record") DataDic record, @Param("example") DataDicSchema example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_datadic
     *
     * @mbggenerated Sun Oct 11 19:42:52 CST 2015
     */
    int updateByPrimaryKeySelective(DataDic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_datadic
     *
     * @mbggenerated Sun Oct 11 19:42:52 CST 2015
     */
    int updateByPrimaryKey(DataDic record);
}