package com.base.mapper;

import com.base.domain.ManagerAccount;
import com.base.domain.ManagerAccountSchema;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ManagerAccountMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_manageraccount
     *
     * @mbggenerated Mon Oct 12 21:40:50 CST 2015
     */
    int countByExample(ManagerAccountSchema example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_manageraccount
     *
     * @mbggenerated Mon Oct 12 21:40:50 CST 2015
     */
    int deleteByExample(ManagerAccountSchema example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_manageraccount
     *
     * @mbggenerated Mon Oct 12 21:40:50 CST 2015
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_manageraccount
     *
     * @mbggenerated Mon Oct 12 21:40:50 CST 2015
     */
    int insert(ManagerAccount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_manageraccount
     *
     * @mbggenerated Mon Oct 12 21:40:50 CST 2015
     */
    int insertSelective(ManagerAccount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_manageraccount
     *
     * @mbggenerated Mon Oct 12 21:40:50 CST 2015
     */
    List<ManagerAccount> selectByExample(ManagerAccountSchema example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_manageraccount
     *
     * @mbggenerated Mon Oct 12 21:40:50 CST 2015
     */
    ManagerAccount selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_manageraccount
     *
     * @mbggenerated Mon Oct 12 21:40:50 CST 2015
     */
    int updateByExampleSelective(@Param("record") ManagerAccount record, @Param("example") ManagerAccountSchema example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_manageraccount
     *
     * @mbggenerated Mon Oct 12 21:40:50 CST 2015
     */
    int updateByExample(@Param("record") ManagerAccount record, @Param("example") ManagerAccountSchema example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_manageraccount
     *
     * @mbggenerated Mon Oct 12 21:40:50 CST 2015
     */
    int updateByPrimaryKeySelective(ManagerAccount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_manageraccount
     *
     * @mbggenerated Mon Oct 12 21:40:50 CST 2015
     */
    int updateByPrimaryKey(ManagerAccount record);
}