package com.base.mapper;

import com.base.domain.Menu;
import com.base.domain.MenuSchema;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MenuMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_menu
     *
     * @mbggenerated Sun Oct 18 20:19:01 CST 2015
     */
    int countByExample(MenuSchema example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_menu
     *
     * @mbggenerated Sun Oct 18 20:19:01 CST 2015
     */
    int deleteByExample(MenuSchema example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_menu
     *
     * @mbggenerated Sun Oct 18 20:19:01 CST 2015
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_menu
     *
     * @mbggenerated Sun Oct 18 20:19:01 CST 2015
     */
    int insert(Menu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_menu
     *
     * @mbggenerated Sun Oct 18 20:19:01 CST 2015
     */
    int insertSelective(Menu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_menu
     *
     * @mbggenerated Sun Oct 18 20:19:01 CST 2015
     */
    List<Menu> selectByExample(MenuSchema example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_menu
     *
     * @mbggenerated Sun Oct 18 20:19:01 CST 2015
     */
    Menu selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_menu
     *
     * @mbggenerated Sun Oct 18 20:19:01 CST 2015
     */
    int updateByExampleSelective(@Param("record") Menu record, @Param("example") MenuSchema example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_menu
     *
     * @mbggenerated Sun Oct 18 20:19:01 CST 2015
     */
    int updateByExample(@Param("record") Menu record, @Param("example") MenuSchema example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_menu
     *
     * @mbggenerated Sun Oct 18 20:19:01 CST 2015
     */
    int updateByPrimaryKeySelective(Menu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_menu
     *
     * @mbggenerated Sun Oct 18 20:19:01 CST 2015
     */
    int updateByPrimaryKey(Menu record);
}