package com.base.domain;

public class DataDic extends DataDicKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_datadic.name
     *
     * @mbggenerated Sun Oct 11 19:42:52 CST 2015
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_datadic.alisname
     *
     * @mbggenerated Sun Oct 11 19:42:52 CST 2015
     */
    private String alisname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_datadic.descDetail
     *
     * @mbggenerated Sun Oct 11 19:42:52 CST 2015
     */
    private String descdetail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_datadic.price
     *
     * @mbggenerated Sun Oct 11 19:42:52 CST 2015
     */
    private Integer price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_datadic.Charmvalue
     *
     * @mbggenerated Sun Oct 11 19:42:52 CST 2015
     */
    private Integer charmvalue;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_datadic.name
     *
     * @return the value of t_datadic.name
     *
     * @mbggenerated Sun Oct 11 19:42:52 CST 2015
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_datadic.name
     *
     * @param name the value for t_datadic.name
     *
     * @mbggenerated Sun Oct 11 19:42:52 CST 2015
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_datadic.alisname
     *
     * @return the value of t_datadic.alisname
     *
     * @mbggenerated Sun Oct 11 19:42:52 CST 2015
     */
    public String getAlisname() {
        return alisname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_datadic.alisname
     *
     * @param alisname the value for t_datadic.alisname
     *
     * @mbggenerated Sun Oct 11 19:42:52 CST 2015
     */
    public void setAlisname(String alisname) {
        this.alisname = alisname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_datadic.descDetail
     *
     * @return the value of t_datadic.descDetail
     *
     * @mbggenerated Sun Oct 11 19:42:52 CST 2015
     */
    public String getDescdetail() {
        return descdetail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_datadic.descDetail
     *
     * @param descdetail the value for t_datadic.descDetail
     *
     * @mbggenerated Sun Oct 11 19:42:52 CST 2015
     */
    public void setDescdetail(String descdetail) {
        this.descdetail = descdetail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_datadic.price
     *
     * @return the value of t_datadic.price
     *
     * @mbggenerated Sun Oct 11 19:42:52 CST 2015
     */
    public Integer getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_datadic.price
     *
     * @param price the value for t_datadic.price
     *
     * @mbggenerated Sun Oct 11 19:42:52 CST 2015
     */
    public void setPrice(Integer price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_datadic.Charmvalue
     *
     * @return the value of t_datadic.Charmvalue
     *
     * @mbggenerated Sun Oct 11 19:42:52 CST 2015
     */
    public Integer getCharmvalue() {
        return charmvalue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_datadic.Charmvalue
     *
     * @param charmvalue the value for t_datadic.Charmvalue
     *
     * @mbggenerated Sun Oct 11 19:42:52 CST 2015
     */
    public void setCharmvalue(Integer charmvalue) {
        this.charmvalue = charmvalue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_datadic
     *
     * @mbggenerated Sun Oct 11 19:42:52 CST 2015
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", name=").append(name);
        sb.append(", alisname=").append(alisname);
        sb.append(", descdetail=").append(descdetail);
        sb.append(", price=").append(price);
        sb.append(", charmvalue=").append(charmvalue);
        sb.append("]");
        return sb.toString();
    }
}