package com.base.domain;

import com.base.page.Page;
import java.util.ArrayList;
import java.util.List;

public class DataDicSchema {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_datadic
     *
     * @mbggenerated Sun Oct 11 19:42:52 CST 2015
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_datadic
     *
     * @mbggenerated Sun Oct 11 19:42:52 CST 2015
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_datadic
     *
     * @mbggenerated Sun Oct 11 19:42:52 CST 2015
     */
    protected List<Criteria> oredCriteria;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_datadic
     *
     * @mbggenerated Sun Oct 11 19:42:52 CST 2015
     */
    protected Page page;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_datadic
     *
     * @mbggenerated Sun Oct 11 19:42:52 CST 2015
     */
    public DataDicSchema() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_datadic
     *
     * @mbggenerated Sun Oct 11 19:42:52 CST 2015
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_datadic
     *
     * @mbggenerated Sun Oct 11 19:42:52 CST 2015
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_datadic
     *
     * @mbggenerated Sun Oct 11 19:42:52 CST 2015
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_datadic
     *
     * @mbggenerated Sun Oct 11 19:42:52 CST 2015
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_datadic
     *
     * @mbggenerated Sun Oct 11 19:42:52 CST 2015
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_datadic
     *
     * @mbggenerated Sun Oct 11 19:42:52 CST 2015
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_datadic
     *
     * @mbggenerated Sun Oct 11 19:42:52 CST 2015
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_datadic
     *
     * @mbggenerated Sun Oct 11 19:42:52 CST 2015
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_datadic
     *
     * @mbggenerated Sun Oct 11 19:42:52 CST 2015
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_datadic
     *
     * @mbggenerated Sun Oct 11 19:42:52 CST 2015
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_datadic
     *
     * @mbggenerated Sun Oct 11 19:42:52 CST 2015
     */
    public void setPage(Page page) {
        this.page=page;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_datadic
     *
     * @mbggenerated Sun Oct 11 19:42:52 CST 2015
     */
    public Page getPage() {
        return page;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_datadic
     *
     * @mbggenerated Sun Oct 11 19:42:52 CST 2015
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andCodetypeIsNull() {
            addCriterion("codetype is null");
            return (Criteria) this;
        }

        public Criteria andCodetypeIsNotNull() {
            addCriterion("codetype is not null");
            return (Criteria) this;
        }

        public Criteria andCodetypeEqualTo(String value) {
            addCriterion("codetype =", value, "codetype");
            return (Criteria) this;
        }

        public Criteria andCodetypeNotEqualTo(String value) {
            addCriterion("codetype <>", value, "codetype");
            return (Criteria) this;
        }

        public Criteria andCodetypeGreaterThan(String value) {
            addCriterion("codetype >", value, "codetype");
            return (Criteria) this;
        }

        public Criteria andCodetypeGreaterThanOrEqualTo(String value) {
            addCriterion("codetype >=", value, "codetype");
            return (Criteria) this;
        }

        public Criteria andCodetypeLessThan(String value) {
            addCriterion("codetype <", value, "codetype");
            return (Criteria) this;
        }

        public Criteria andCodetypeLessThanOrEqualTo(String value) {
            addCriterion("codetype <=", value, "codetype");
            return (Criteria) this;
        }

        public Criteria andCodetypeLike(String value) {
            addCriterion("codetype like", value, "codetype");
            return (Criteria) this;
        }

        public Criteria andCodetypeNotLike(String value) {
            addCriterion("codetype not like", value, "codetype");
            return (Criteria) this;
        }

        public Criteria andCodetypeIn(List<String> values) {
            addCriterion("codetype in", values, "codetype");
            return (Criteria) this;
        }

        public Criteria andCodetypeNotIn(List<String> values) {
            addCriterion("codetype not in", values, "codetype");
            return (Criteria) this;
        }

        public Criteria andCodetypeBetween(String value1, String value2) {
            addCriterion("codetype between", value1, value2, "codetype");
            return (Criteria) this;
        }

        public Criteria andCodetypeNotBetween(String value1, String value2) {
            addCriterion("codetype not between", value1, value2, "codetype");
            return (Criteria) this;
        }

        public Criteria andCodeIsNull() {
            addCriterion("code is null");
            return (Criteria) this;
        }

        public Criteria andCodeIsNotNull() {
            addCriterion("code is not null");
            return (Criteria) this;
        }

        public Criteria andCodeEqualTo(String value) {
            addCriterion("code =", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeNotEqualTo(String value) {
            addCriterion("code <>", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeGreaterThan(String value) {
            addCriterion("code >", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeGreaterThanOrEqualTo(String value) {
            addCriterion("code >=", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeLessThan(String value) {
            addCriterion("code <", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeLessThanOrEqualTo(String value) {
            addCriterion("code <=", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeLike(String value) {
            addCriterion("code like", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeNotLike(String value) {
            addCriterion("code not like", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeIn(List<String> values) {
            addCriterion("code in", values, "code");
            return (Criteria) this;
        }

        public Criteria andCodeNotIn(List<String> values) {
            addCriterion("code not in", values, "code");
            return (Criteria) this;
        }

        public Criteria andCodeBetween(String value1, String value2) {
            addCriterion("code between", value1, value2, "code");
            return (Criteria) this;
        }

        public Criteria andCodeNotBetween(String value1, String value2) {
            addCriterion("code not between", value1, value2, "code");
            return (Criteria) this;
        }

        public Criteria andNameIsNull() {
            addCriterion("name is null");
            return (Criteria) this;
        }

        public Criteria andNameIsNotNull() {
            addCriterion("name is not null");
            return (Criteria) this;
        }

        public Criteria andNameEqualTo(String value) {
            addCriterion("name =", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotEqualTo(String value) {
            addCriterion("name <>", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThan(String value) {
            addCriterion("name >", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThanOrEqualTo(String value) {
            addCriterion("name >=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThan(String value) {
            addCriterion("name <", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThanOrEqualTo(String value) {
            addCriterion("name <=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLike(String value) {
            addCriterion("name like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotLike(String value) {
            addCriterion("name not like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameIn(List<String> values) {
            addCriterion("name in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotIn(List<String> values) {
            addCriterion("name not in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameBetween(String value1, String value2) {
            addCriterion("name between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotBetween(String value1, String value2) {
            addCriterion("name not between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andAlisnameIsNull() {
            addCriterion("alisname is null");
            return (Criteria) this;
        }

        public Criteria andAlisnameIsNotNull() {
            addCriterion("alisname is not null");
            return (Criteria) this;
        }

        public Criteria andAlisnameEqualTo(String value) {
            addCriterion("alisname =", value, "alisname");
            return (Criteria) this;
        }

        public Criteria andAlisnameNotEqualTo(String value) {
            addCriterion("alisname <>", value, "alisname");
            return (Criteria) this;
        }

        public Criteria andAlisnameGreaterThan(String value) {
            addCriterion("alisname >", value, "alisname");
            return (Criteria) this;
        }

        public Criteria andAlisnameGreaterThanOrEqualTo(String value) {
            addCriterion("alisname >=", value, "alisname");
            return (Criteria) this;
        }

        public Criteria andAlisnameLessThan(String value) {
            addCriterion("alisname <", value, "alisname");
            return (Criteria) this;
        }

        public Criteria andAlisnameLessThanOrEqualTo(String value) {
            addCriterion("alisname <=", value, "alisname");
            return (Criteria) this;
        }

        public Criteria andAlisnameLike(String value) {
            addCriterion("alisname like", value, "alisname");
            return (Criteria) this;
        }

        public Criteria andAlisnameNotLike(String value) {
            addCriterion("alisname not like", value, "alisname");
            return (Criteria) this;
        }

        public Criteria andAlisnameIn(List<String> values) {
            addCriterion("alisname in", values, "alisname");
            return (Criteria) this;
        }

        public Criteria andAlisnameNotIn(List<String> values) {
            addCriterion("alisname not in", values, "alisname");
            return (Criteria) this;
        }

        public Criteria andAlisnameBetween(String value1, String value2) {
            addCriterion("alisname between", value1, value2, "alisname");
            return (Criteria) this;
        }

        public Criteria andAlisnameNotBetween(String value1, String value2) {
            addCriterion("alisname not between", value1, value2, "alisname");
            return (Criteria) this;
        }

        public Criteria andDescdetailIsNull() {
            addCriterion("descDetail is null");
            return (Criteria) this;
        }

        public Criteria andDescdetailIsNotNull() {
            addCriterion("descDetail is not null");
            return (Criteria) this;
        }

        public Criteria andDescdetailEqualTo(String value) {
            addCriterion("descDetail =", value, "descdetail");
            return (Criteria) this;
        }

        public Criteria andDescdetailNotEqualTo(String value) {
            addCriterion("descDetail <>", value, "descdetail");
            return (Criteria) this;
        }

        public Criteria andDescdetailGreaterThan(String value) {
            addCriterion("descDetail >", value, "descdetail");
            return (Criteria) this;
        }

        public Criteria andDescdetailGreaterThanOrEqualTo(String value) {
            addCriterion("descDetail >=", value, "descdetail");
            return (Criteria) this;
        }

        public Criteria andDescdetailLessThan(String value) {
            addCriterion("descDetail <", value, "descdetail");
            return (Criteria) this;
        }

        public Criteria andDescdetailLessThanOrEqualTo(String value) {
            addCriterion("descDetail <=", value, "descdetail");
            return (Criteria) this;
        }

        public Criteria andDescdetailLike(String value) {
            addCriterion("descDetail like", value, "descdetail");
            return (Criteria) this;
        }

        public Criteria andDescdetailNotLike(String value) {
            addCriterion("descDetail not like", value, "descdetail");
            return (Criteria) this;
        }

        public Criteria andDescdetailIn(List<String> values) {
            addCriterion("descDetail in", values, "descdetail");
            return (Criteria) this;
        }

        public Criteria andDescdetailNotIn(List<String> values) {
            addCriterion("descDetail not in", values, "descdetail");
            return (Criteria) this;
        }

        public Criteria andDescdetailBetween(String value1, String value2) {
            addCriterion("descDetail between", value1, value2, "descdetail");
            return (Criteria) this;
        }

        public Criteria andDescdetailNotBetween(String value1, String value2) {
            addCriterion("descDetail not between", value1, value2, "descdetail");
            return (Criteria) this;
        }

        public Criteria andPriceIsNull() {
            addCriterion("price is null");
            return (Criteria) this;
        }

        public Criteria andPriceIsNotNull() {
            addCriterion("price is not null");
            return (Criteria) this;
        }

        public Criteria andPriceEqualTo(Integer value) {
            addCriterion("price =", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceNotEqualTo(Integer value) {
            addCriterion("price <>", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceGreaterThan(Integer value) {
            addCriterion("price >", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceGreaterThanOrEqualTo(Integer value) {
            addCriterion("price >=", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceLessThan(Integer value) {
            addCriterion("price <", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceLessThanOrEqualTo(Integer value) {
            addCriterion("price <=", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceIn(List<Integer> values) {
            addCriterion("price in", values, "price");
            return (Criteria) this;
        }

        public Criteria andPriceNotIn(List<Integer> values) {
            addCriterion("price not in", values, "price");
            return (Criteria) this;
        }

        public Criteria andPriceBetween(Integer value1, Integer value2) {
            addCriterion("price between", value1, value2, "price");
            return (Criteria) this;
        }

        public Criteria andPriceNotBetween(Integer value1, Integer value2) {
            addCriterion("price not between", value1, value2, "price");
            return (Criteria) this;
        }

        public Criteria andCharmvalueIsNull() {
            addCriterion("Charmvalue is null");
            return (Criteria) this;
        }

        public Criteria andCharmvalueIsNotNull() {
            addCriterion("Charmvalue is not null");
            return (Criteria) this;
        }

        public Criteria andCharmvalueEqualTo(Integer value) {
            addCriterion("Charmvalue =", value, "charmvalue");
            return (Criteria) this;
        }

        public Criteria andCharmvalueNotEqualTo(Integer value) {
            addCriterion("Charmvalue <>", value, "charmvalue");
            return (Criteria) this;
        }

        public Criteria andCharmvalueGreaterThan(Integer value) {
            addCriterion("Charmvalue >", value, "charmvalue");
            return (Criteria) this;
        }

        public Criteria andCharmvalueGreaterThanOrEqualTo(Integer value) {
            addCriterion("Charmvalue >=", value, "charmvalue");
            return (Criteria) this;
        }

        public Criteria andCharmvalueLessThan(Integer value) {
            addCriterion("Charmvalue <", value, "charmvalue");
            return (Criteria) this;
        }

        public Criteria andCharmvalueLessThanOrEqualTo(Integer value) {
            addCriterion("Charmvalue <=", value, "charmvalue");
            return (Criteria) this;
        }

        public Criteria andCharmvalueIn(List<Integer> values) {
            addCriterion("Charmvalue in", values, "charmvalue");
            return (Criteria) this;
        }

        public Criteria andCharmvalueNotIn(List<Integer> values) {
            addCriterion("Charmvalue not in", values, "charmvalue");
            return (Criteria) this;
        }

        public Criteria andCharmvalueBetween(Integer value1, Integer value2) {
            addCriterion("Charmvalue between", value1, value2, "charmvalue");
            return (Criteria) this;
        }

        public Criteria andCharmvalueNotBetween(Integer value1, Integer value2) {
            addCriterion("Charmvalue not between", value1, value2, "charmvalue");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_datadic
     *
     * @mbggenerated do_not_delete_during_merge Sun Oct 11 19:42:52 CST 2015
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_datadic
     *
     * @mbggenerated Sun Oct 11 19:42:52 CST 2015
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}