package com.base.domain;

public class DataDicKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_datadic.codetype
     *
     * @mbggenerated Sun Oct 11 19:42:52 CST 2015
     */
    private String codetype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_datadic.code
     *
     * @mbggenerated Sun Oct 11 19:42:52 CST 2015
     */
    private String code;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_datadic.codetype
     *
     * @return the value of t_datadic.codetype
     *
     * @mbggenerated Sun Oct 11 19:42:52 CST 2015
     */
    public String getCodetype() {
        return codetype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_datadic.codetype
     *
     * @param codetype the value for t_datadic.codetype
     *
     * @mbggenerated Sun Oct 11 19:42:52 CST 2015
     */
    public void setCodetype(String codetype) {
        this.codetype = codetype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_datadic.code
     *
     * @return the value of t_datadic.code
     *
     * @mbggenerated Sun Oct 11 19:42:52 CST 2015
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_datadic.code
     *
     * @param code the value for t_datadic.code
     *
     * @mbggenerated Sun Oct 11 19:42:52 CST 2015
     */
    public void setCode(String code) {
        this.code = code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_datadic
     *
     * @mbggenerated Sun Oct 11 19:42:52 CST 2015
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", codetype=").append(codetype);
        sb.append(", code=").append(code);
        sb.append("]");
        return sb.toString();
    }
}