package com.base.domain;

public class ManagerAccount {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_manageraccount.id
     *
     * @mbggenerated Mon Oct 12 21:40:50 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_manageraccount.userCode
     *
     * @mbggenerated Mon Oct 12 21:40:50 CST 2015
     */
    private String usercode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_manageraccount.password
     *
     * @mbggenerated Mon Oct 12 21:40:50 CST 2015
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_manageraccount.phone
     *
     * @mbggenerated Mon Oct 12 21:40:50 CST 2015
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_manageraccount.userName
     *
     * @mbggenerated Mon Oct 12 21:40:50 CST 2015
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_manageraccount.registTime
     *
     * @mbggenerated Mon Oct 12 21:40:50 CST 2015
     */
    private String registtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_manageraccount.createTime
     *
     * @mbggenerated Mon Oct 12 21:40:50 CST 2015
     */
    private String createtime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_manageraccount.id
     *
     * @return the value of t_manageraccount.id
     *
     * @mbggenerated Mon Oct 12 21:40:50 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_manageraccount.id
     *
     * @param id the value for t_manageraccount.id
     *
     * @mbggenerated Mon Oct 12 21:40:50 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_manageraccount.userCode
     *
     * @return the value of t_manageraccount.userCode
     *
     * @mbggenerated Mon Oct 12 21:40:50 CST 2015
     */
    public String getUsercode() {
        return usercode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_manageraccount.userCode
     *
     * @param usercode the value for t_manageraccount.userCode
     *
     * @mbggenerated Mon Oct 12 21:40:50 CST 2015
     */
    public void setUsercode(String usercode) {
        this.usercode = usercode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_manageraccount.password
     *
     * @return the value of t_manageraccount.password
     *
     * @mbggenerated Mon Oct 12 21:40:50 CST 2015
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_manageraccount.password
     *
     * @param password the value for t_manageraccount.password
     *
     * @mbggenerated Mon Oct 12 21:40:50 CST 2015
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_manageraccount.phone
     *
     * @return the value of t_manageraccount.phone
     *
     * @mbggenerated Mon Oct 12 21:40:50 CST 2015
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_manageraccount.phone
     *
     * @param phone the value for t_manageraccount.phone
     *
     * @mbggenerated Mon Oct 12 21:40:50 CST 2015
     */
    public void setPhone(String phone) {
        this.phone = phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_manageraccount.userName
     *
     * @return the value of t_manageraccount.userName
     *
     * @mbggenerated Mon Oct 12 21:40:50 CST 2015
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_manageraccount.userName
     *
     * @param username the value for t_manageraccount.userName
     *
     * @mbggenerated Mon Oct 12 21:40:50 CST 2015
     */
    public void setUsername(String username) {
        this.username = username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_manageraccount.registTime
     *
     * @return the value of t_manageraccount.registTime
     *
     * @mbggenerated Mon Oct 12 21:40:50 CST 2015
     */
    public String getRegisttime() {
        return registtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_manageraccount.registTime
     *
     * @param registtime the value for t_manageraccount.registTime
     *
     * @mbggenerated Mon Oct 12 21:40:50 CST 2015
     */
    public void setRegisttime(String registtime) {
        this.registtime = registtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_manageraccount.createTime
     *
     * @return the value of t_manageraccount.createTime
     *
     * @mbggenerated Mon Oct 12 21:40:50 CST 2015
     */
    public String getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_manageraccount.createTime
     *
     * @param createtime the value for t_manageraccount.createTime
     *
     * @mbggenerated Mon Oct 12 21:40:50 CST 2015
     */
    public void setCreatetime(String createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_manageraccount
     *
     * @mbggenerated Mon Oct 12 21:40:50 CST 2015
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", usercode=").append(usercode);
        sb.append(", password=").append(password);
        sb.append(", phone=").append(phone);
        sb.append(", username=").append(username);
        sb.append(", registtime=").append(registtime);
        sb.append(", createtime=").append(createtime);
        sb.append("]");
        return sb.toString();
    }
}